### ISSUE TITLE
Teams and Teams2

### ISSUE THREAD

**Issue by vmeyer9086** [linville/qoc-jrnats#4]
- [x] No College teams listed in Teams.
- [x] JROTC needs to have Varsity and JV sections in Teams2.

**Comment by linville** [comment]
Do we expect any ICJV teams? A previous commit changed IC teams to be imported as ICV.

https://github.com/linville/qoc-jrnats/blob/6e4c57fe39cdacbd42895819161530839fb924e1/app/controllers/teams_controller.rb#L20

**Comment by linville** [comment]
> * JROTC needs to have Varsity and JV sections in Teams2.

@vmeyer9086, should this a new column with two sections (V and JV)?

**Comment by vmeyer9086** [comment]
Because of space I would probably put in the ISI column. I can move things around...

Valerie

**Comment by vmeyer9086** [comment]
No. Something for future fix. :)

Valerie

**Comment by vmeyer9086** [comment]
I see now...add the JROTC categories to the Teams2Controller index?
 Really enjoy figuring this stuff out, so hopefully not driving you nuts.

Edit April 1 - I will do this tomorrow.

**Comment by vmeyer9086** [comment]
All categories now present in the Team results.
