### ISSUE TITLE
view/awards

### ISSUE THREAD

**Issue by vmeyer9086** [linville/qoc-jrnats#5]
Put placeholders in for the JV/V F/M JROTC - they place as individuals as well as on teams.  So, are eligible for two individual medals - top 3 in their category, and top 3 in NJROTC.

Need  help pulling them out.

**Comment by vmeyer9086** [comment]
So, for individual results, it would be isjvf_jrotc, isjvm_jrotc, isvf_jrotc, and ismv_jrotc, added to the view awards index?

**Comment by vmeyer9086** [comment]
Added a "jrotc" field to the db - migrated it, and it shows as jrotc in the db.  Also added the field to controller/runner.

Now trying to figure out how to populate the field in model/runner.  Tried a bunch of things today, for hours (I am subborn), but no joy.  Would like runner/jrotc field to have an entry if Text3 controls JROTC, and be blank, if Text3 doesn't include JROTC.

```
CSV.foreach(file.path, headers: true) do |row|
      if row["OE0002"] == "***"
        skipped += 1
      elsif row["Short"].start_with? "I"
        if row["Text1"]
          school = row["Text1"]
        else
          school = "Unknown"
        end
        
        runner = Runner.create(database_id: row["Stno"],
                      surname: row["Surname"].gsub("'"){"\\'"},
                      firstname: row["First name"].gsub("'"){"\\'"},
                      school: school.gsub("'"){"\\'"},
                      entryclass: row["Short"],
                      gender: row['S'])
        added += 1
        
        # Runner is created,
```

**Comment by linville** [comment]
It'll probably be something like this:

```diff
+jrotc = false
+if row['Text3'].include? "JROTC"
+  jrotc = true
+end

runner = Runner.create(database_id: row["Stno"],
                      surname: row["Surname"].gsub("'"){"\\'"},
                      firstname: row["First name"].gsub("'"){"\\'"},
                      school: school.gsub("'"){"\\'"},
                      entryclass: row["Short"],
+                     jrotc:jrotc,
                      gender: row['S'])
```

**Comment by vmeyer9086** [comment]
Thank you so much!  I was able to get that to work, with a little edit to suit, and now I can go to bed!
Tomorrow, I will fix the other things.  I think we are getting close.
Valerie

-----Original Message-----

**Comment by vmeyer9086** [comment]
Resolved.

**Comment by vmeyer9086** [comment]
When I go to print the top 3 awards results as shown on the screen, the name and school columns wrap to the next line. 

Is the issue in the table format, or the fact that the 2019 QOC title spans the page?

**Comment by vmeyer9086** [comment]
OK, fixed it.  Looks funny on the screen being full width, but prints correctly, and that is all that matters.
