### ISSUE TITLE
ISI classes and JROTC

### ISSUE THREAD

**Issue by linville** [linville/qoc-jrnats#7]
In EventReg there isn't a Team Category "Intermediate School and JROTC" so ISI class runners, who are JROTC, won't have the JROTC field correctly filled in (and unfortunately, the "Affiliated Branch" field is not exported by EventReg). Is this an issue?

https://github.com/linville/qoc-jrnats/blob/fd71b66548ed25fd249db7d6d816e68efe95129c/app/models/runner.rb#L18

**Comment by vmeyer9086** [comment]
There are not separate awards for Intermediate School JROTC members, so this can be ignored.
